SELECT * FROM customer limit 20


-- 1. what is the  total revenue generated by Male vs Female Customers?

SELECT
    gender,
    SUM(purchace_amount) AS revenue
FROM customer
GROUP BY gender;

-- 2. which customer used a discount but still spent more than  the average purchase amount

select customer_id , purchace_amount from customer
where discount_applied = 'Yes' 
and purchace_amount >= (select AVG(purchace_amount) from customer)

--3. which are the top 5 products with the  highest  average review rating ?
select item_purchased ,round(AVG(review_rating :: numeric),2) as "Average Product Rating"
From customer 
group by item_purchased
order by avg (review_rating) desc
limit 5 ;

--4 . compare the average purchase amount between standard and express shipping ?
select shipping_type ,
round(avg(purchace_amount),2)
from customer 
where shipping_type in ('Standard','Express')
group by shipping_type 

--5 do subscribed customer spend more ? compare average spend and total revenue between subscribes and non-subscribes .
select subscription_status , 
count(customer_id) as total_customer,
round(avg(purchace_amount),2) as avg_spend ,
round(sum(purchace_amount),2) as total_revenue 
from customer
group by subscription_status
order by avg_spend , total_revenue desc ;

--6 . which 5 product have the highest percentage of purchase with discount applied ?
SELECT
    item_purchased,
    ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
        / COUNT(*),
        2
    ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--7. segment customer into new , returning and loyal based on theri total number of previous purchase and show the count of each segmnet .

with customer_type as (
select customer_id , previous_purchases,
case 
	when previous_purchases = 1 then 'new'
	when previous_purchases between 2 and 15 then 'Returning'
	else 'loyal'
	end as customer_segment 
from customer 
)

select customer_segment , count(*) as "No of Customers"
from customer_type
group by customer_segment

--8 what are the top 3 most purchased producte within each category ?

with item_counts as (
select category ,
item_purchased ,
count (customer_id) as total_orders ,
row_number() over(partition by category order by count(customer_id)desc) as item_rank
from customer
group by category , item_purchased
)

select item_rank , category , item_purchased , total_orders
from item_counts
where item_rank <= 3;
)

-- 9.Are customer who are repeat buyers (more thn 5 previous purchases ) also likely to subscribe

select subscription_status ,
count (customer_id) as repeat_buyers
from customer 
where previous_purchases > 5
group by subscription_status

--10 .what is the revenue  contribution of each group ?

select age_group ,
sum(purchace_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;




